try again

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -64,16 +64,20 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: '17'
-      - name: Install and set Flutter version
-        uses: subosito/flutter-action@v2
-        with:
-          channel: 'stable'
       - name: Create the Keystore
         env:
           KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
         run: |
           echo "$KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
           ls
+      - name: Verify Keystore
+        run: |
+          keytool -list -v -keystore android/app/upload-keystore.jks \
+            -storepass ${{ secrets.KEYSTORE_PASSWORD }} || echo "Keystore verification failed"
+      - name: Install and set Flutter version
+        uses: subosito/flutter-action@v2
+        with:
+          channel: 'stable'
       - name: Create key.properties
         run: |
             cat > android/key.properties << EOF
